#     _______               __          __
#    |__   __|              \ \        / /
#       | | ___  __ _ _ __ __\ \  /\  / /_ _ _ __ ___
#       | |/ _ \/ _` | '_ ` _ \ \/  \/ / _` | '__/ __|
#       | |  __/ (_| | | | | | \  /\  / (_| | |  \__ \
#       |_|\___|\__,_|_| |_| |_|\/  \/ \__,_|_|  |___/
#
#       Created by zManuel



#Database connection
MONGO:
  HOST: 127.0.0.1
  PORT: 27017
  AUTH:
    ENABLED: false
    DATABASE: 'admin'
    USERNAME: ''
    PASSWORD: ''